# Generated by Django 3.2.16 on 2022-12-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=25)),
                ('photo', models.ImageField(upload_to='seller/')),
                ('comp_name', models.CharField(max_length=50)),
                ('acc_name', models.CharField(max_length=70)),
                ('ifcs', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=75)),
                ('acc_number', models.CharField(max_length=50)),
            ],
        ),
    ]
