# Generated by Django 3.2.16 on 2022-12-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='ifcs',
            new_name='ifsc',
        ),
    ]
