# Generated by Django 3.2.16 on 2023-01-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_tb',
        ),
    ]
