# Generated by Django 3.2.16 on 2022-12-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
